name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # or 20 if you're using a newer version

      # Step 3: Install Railway CLI globally
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      # Step 4: Install dependencies from your package.json
      - name: Install dependencies
        run: npm install

      # Step 5: Deploy your app to Railway using your secret token
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service Linkr
